apiVersion: power.k8s.local/v1alpha1
kind: NodePowerGroup
metadata:
  labels:
    app.kubernetes.io/name: node-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: nodepowergroup-sample
spec:
  # TODO(user): Add fields here
